# Generated by Django 2.0.13 on 2019-06-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0002_servico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='Service',
        ),
    ]
