# Generated by Django 2.0.13 on 2019-06-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0003_auto_20190611_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
