# Generated by Django 2.0.13 on 2019-06-18 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0005_auto_20190617_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="O número deve estar no seguinte formato: '+999999999'. São permitidos até 15 digitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='consultoria.Service'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('CONTATO FEITO', 'Realizado contato'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado')], default='NOVO', max_length=30),
        ),
    ]
